#!/bin/bash

#xrandr --output DisplayPort-1 --off

killall compton 

xrandr --output HDMI-A-1 --off

xrandr --output DisplayPort-1 --primary --mode 1920x1080 --rate 74.97 --rotate normal

killall polybar
polybar left &
compton &