#!/bin/bash

sudo pacman -S base-devel git subversion cmake libxi libxcursor libxrandr libxinerama boost

mkdir -p $HOME/blender-git

cd $HOME/blender-git

git clone https://git.blender.org/blender.git

mkdir -p $HOME/blender-git/lib

cd $HOME/blender-git/lib

svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64/

cd $HOME/blender-git/blender 

make update
make full

sudo cp $HOME/blender-git/build_linux_full/bin/blender /bin

sudo cp $DOTFILES_DIR/Configs/blender.desktop /usr/share/applications

