#!/bin/bash

sudo cp $DOTFILES_DIR/Scripts/setupScripts/installBlender /bin
sudo cp $DOTFILES_DIR/Scripts/setupScripts/installGodot /bin
sudo cp $DOTFILES_DIR/Scripts/setupScripts/installKrita /bin
sudo cp $DOTFILES_DIR/Scripts/bashScripts/newsAndEntertainmentSync /bin
sudo cp $DOTFILES_DIR/Scripts/bashScripts/xauuuuuuuu /bin
sudo cp $DOTFILES_DIR/Scripts/bashScripts/workingTime /bin
sudo cp $DOTFILES_DIR/Scripts/bashScripts/drawingMode /bin

sudo cp $DOTFILES_DIR/Scripts/setupScripts/update* /bin