#!/bin/bash
echo "Important! Run this inside the dotfiles folder!"
sleep 2

echo "Also, only do this AFTER you completed Artix Linux installation! Follow guide on artix-install-help.txt"
sleep 2

cd ~

echo "Installing essential Arch apps..."

sleep 1

sudo pacman -S xorg-server git xorg-xinit awesome rxvt-unicode lightdm lightdm-webkit-greeter pamixer pulseaudio pulseaudio-alsa alsa-utils w3m polkit-gnome

sudo ln -s /etc/runit/sv/lightdm /run/runit/service/

sleep 1

echo "loadkeys pt" | tee -a ~/.xinitrc

echo "export LANG=en_GB.UTF-8" | tee -a ~/.bashrc 
echo "export LANGUAGE=en_GB.UTF-8" | tee -a ~/.bashrc
echo "xrdb merge ~/.Xresources" | tee -a ~/.bashrc

cd Downloads

echo "Downloading and installing yay..."
sleep 1

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

#### Actual setup

laptop="laptop"
desktop="desktop"

read -p "On which device are you installing my dude? 'laptop' or 'desktop'?  " device

echo "Got you fam, installing on $device."
./Scripts/bashScripts/addToPath

# This is also done right now so that the rest of the script can go along nicely, even without a reboot
export DOTFILES_DIR=$DOTFILES_DIR
export PATH=$PATH:$DOTFILES_DIR

cd Scripts

./touchInitialFiles

./installRicePrograms $device

# Remove fish intro message
echo 'set -U fish_greeting ""' >> .config/fish/config.fish

echo "There is a list of programs at Scripts/setupScripts/extraProgramsToInstall . You can modify this file now if you want, to download exactly what you need!"
sleep 2

read -p "Do you want to install the extra programs at Scripts/setupScripts/extraProgramsToInstall.sh? (y/n)  " answer
if [ $answer == "y" ]
then 
	./setupScripts/extraProgramsToInstall.sh $device "arch-based"
fi

./setupLightDM.sh 

./setupSpicetify.sh

# Fix small ranger error 
echo "set preview_script $HOME/.config/ranger/scope.sh" >> Apps/ranger/rc.conf

echo "\nSetting up $device configurations..."
sleep 1

./update.sh $device

cd $DOTFILES_DIR/Scripts/setupScripts/

./moveScriptsToBin

cd $DOTFILES_DIR/Scripts

./installFonts
killall i3bar
	
if [ $device == $laptop ]
then
	polybar main

	echo "Configuring TLP for better battery management..."
	sleep 1

	./setupTLP

	read -p "Do you want to setup Prime? (y/n)  " answer

	if [ $answer == "y" ]
	then 
		sudo pacman -S nvidia lib32-nvidia-utils xf86-video-intel nvidia-prime
		sudo mv $DOTFILES_DIR/Configs/30-nvidia.conf /etc/X11/xorg.conf.d/
	fi 

elif [ $device == $desktop ]
then
	./tabletConfig
	polybar left && polybar right
fi

# Installing GRUB theme 
echo "Installing GRUB theme..."
sleep 1

sudo $DOTFILES_DIR/Apps/grub/install.sh -v

# First wal run
python $DOTFILES_DIR/Scripts/pythonScripts/wallpaperAndColorScheme.py

# Fix small error for VLC downloading
mkdir ~/.cache/vlc

echo "Setting up WPGTK theme... (CHANGE LATER WITH LXAPPEARANCE TO FLATCOLOR THEME AND ICON PACK)"
sleep 3

wpg-install.sh -i
wpg-install.sh -g

echo "Change line 93 of this script if you want another lockscreen wallpaper."
sleep 2 

betterlockscreen -u $DOTFILES_DIR/Wallpapers/wallhaven-83do1o.jpg 

echo "If you want to configure VPN, you can do it now."
sleep 3

echo "And that's it! Exiting."
sleep 2


