#!/bin/bash

echo "Configuring apps..."
sleep 0.1

cd $DOTFILES_DIR/Apps

cp -r ranger $HOME/.config/

cp -r krita/Config/krita*rc $HOME/.config/
cp -a krita/Config/KritaPywal.colors $HOME/.config/wal/templates

cp -r krita/Resources/* $HOME/.local/share/krita/

cp -r polybar/* $HOME/.config/polybar/

cd $DOTFILES_DIR/Configs

cp redshift.conf $HOME/.config/

cp compton.conf $HOME/.config/compton.conf
cp picom.conf $HOME/.config/picom.conf

# Dunst and Xresources needs to be updated, and then sent to it's place
cp dunstrc $HOME/.config/wal/templates
cp -a .Xresources $HOME/.config/wal/templates
cp -a .Xresources $HOME/.config/wal/templates
cp -a rofi.rasi $HOME/.config/wal/templates

cp $HOME/.cache/wal/dunstrc $HOME/.config/dunst/
cp $HOME/.cache/wal/.Xresources $HOME/

cp $DOTFILES_DIR/Configs/config.ini $HOME/.config/spicetify

cp -r $DOTFILES_DIR/Apps/spicetify/* $HOME/.config/spicetify/Themes/Yoo

spicetify update

echo "Configuring setup..."
sleep 0.1

cd $DOTFILES_DIR/Configs

touch $HOME/.config/i3/config
rm $HOME/.config/i3/config
    
cat i3-common-config i3-windows i3-keybindings i3-autostart i3-specific-config >> $HOME/.config/i3/config
    
cp polybar/config $HOME/.config/polybar

echo "Updated!"
sleep 1

exit 0
