#!/bin/bash

echo "Adding this folder to the PATH environment variable..."
sleep 1

DOTFILES_DIR=${PWD}

echo "

" >> ~/.bashrc
echo "export DOTFILES_DIR=$DOTFILES_DIR" >> ~/.bashrc
echo "export PATH=$PATH:$DOTFILES_DIR:$DOTFILES_DIR/Scripts/bash-scripts:$DOTFILES_DIR/Scripts/setup-scripts" >> ~/.bashrc

source ~/.bashrc

# This is also done right now so that the rest of the script can go along nicely, even without a reboot
export DOTFILES_DIR=$DOTFILES_DIR
export PATH=$PATH:$DOTFILES_DIR:$DOTFILES_DIR/Scripts/bash-scripts:$DOTFILES_DIR/Scripts/setup-scripts

echo "Added!"
sleep 1
