#!/bin/bash

mkdir -p $HOME/.config/i3

touch $HOME/.config/i3/config

mkdir -p $HOME/.config/spicetify/Themes/Yoo

mkdir $HOME/.config/fish
mkdir $HOME/.config/bspwm
mkdir $HOME/.config/sxhkd

mkdir $HOME/.config/dunst

# For Spicetify
sudo mkdir -p /opt/spotify/Apps/zlink/css
sudo touch /opt/spotify/Apps/zlink/css/user.cs
sudo mkdir -p /opt/spotify/Apps/login/css

sudo chown $USER -R /opt/spotify

touch ${HOME}/.config/spotify/prefs

mkdir -p $HOME/.config/polybar

mkdir -p $HOME/.config/rofi