#!/bin/bash

echo "Important! Run this inside the dotfiles folder, and this only works for an i3 Manjaro!"
sleep 2

echo "With that out of the way, good luck, hope everything turns out well!"
sleep 1

./Scripts/setupScripts/commonSetup