#!/bin/bash


laptop="laptop"
desktop="desktop"

echo "Important! Run this inside the dotfiles folder!"
sleep 2

echo "Entering the void..."

sleep 1

sudo xbps-install -Suv
sudo xbps-install -S xorg-minimal xorg-fonts i3-gaps rxvt-unicode tlp powertop lightdm python lightdm-gtk-greeter python-pip pamixer pulseaudio alsa-utils w3m elogind dbus polkit polkit-gnome 

echo "Configuring i3 on boot..."

sudo ln -srf /etc/sv/{dbus,polkitd,elogind} /var/service
sudo ln -sb /etc/sv/dbus /var/service/dbus
sudo ln -sv /etc/sv/polkitd/ /var/service
sudo ln -s /etc/sv/lightdm /var/service/lightdm
sudo ln -s /etc/sv/NetworkManager /var/service
sudo ln -s /etc/sv/tlp /var/service

sleep 1

echo "exec i3" | tee -a ~/.xinitrc  
echo "loadkeys keymap" | tee -a ~/.xinitrc

echo "export LANG=en_GB.UTF-8" | tee -a ~/.bashrc 
echo "export LANGUAGE=en_GB.UTF-8" | tee -a ~/.bashrc
echo "xrdb merge ~/.Xresources" | tee -a ~/.bashrc

laptop="laptop"
desktop="desktop"

read -p "On which device are you installing my dude? 'laptop' or 'desktop'?  " device

sudo xbps-install -S xorg-minimal xorg-fonts xf86-video-intel

echo "Got you fam, installing on $device. Adding this folder to the PATH environment variable... (requires sudo)"
sleep 1

DOTFILES_DIR=${PWD}

sudo touch /etc/profile.d/dotfiles
echo "#!/bin/bash" | sudo tee -a /etc/profile.d/dotfiles
echo "export PATH=DOTFILES_DIR=$DOTFILES_DIR" | sudo tee -a /etc/profile.d/dotfiles
echo "export PATH=$PATH:$DOTFILES_DIR" | sudo tee -a /etc/profile.d/dotfiles

echo "Added!"
sleep 1

# This is also done right now so that the rest of the script can go along nicely, even without a reboot
export DOTFILES_DIR=$DOTFILES_DIR
export PATH=$PATH:$DOTFILES_DIR

echo "Setting up Void repositories..."
sleep 1

sudo xbps-install void-repo-multilib void-repo-multilib-nonfree void-repo-nonfree 
sudo xbps-install -S

echo "Installing Void programs..."
sleep 1

sudo xbps-install wmctrl ranger dmenu dunst ffmpegthumbnailer feh rofi polybar gsimplecal compton flameshot betterlockscreen wpgtk playerctl lxappearance

# Extra packages for Void 
# compton-tryone-git
# pacmixer
# spicetify-cli

echo "There is a list of programs at Scripts/setupScripts/extraProgramsToInstall . You can modify this file now if you want, to download exactly what you need!"
sleep 2

cd Scripts

read -p "Do you want to install the extra programs at Scripts/setupScripts/extraProgramsToInstall? (y/n)  " answer
if [ $answer == "y" ]
then 
	./setupScripts/extraProgramsToInstall $device "void"
fi


./touchInitialFiles

# Fix small spicetify error 
echo "prefs_path       = ${HOME}/.config/spotify/prefs" >> Apps/spicetify/config.ini

# Fix small ranger error 
echo "set preview_script $HOME/.config/ranger/scope.sh" >> Apps/ranger/rc.conf

echo "\nSetting up $device configurations..."
sleep 1

cd $DOTFILES_DIR

./update $device

cd Scripts

./installFonts
	
if [ $device == $laptop ]
then
	polybar main

	read -p "Do you want to setup Prime? (y/n)  " answer

	if [ $answer == "y" ]
	then 
		sudo xbps-install -S nvidia lib32-nvidia-utils xf86-video-intel
		sudo mv $DOTFILES_DIR/Configs/30-nvidia.conf /etc/X11/xorg.conf.d/
	fi 

elif [ $device == $desktop ]
then
	./tabletConfig
	polybar left && polybar right
fi

cd $DOTFILES_DIR/Scripts/setupScripts/

./moveScriptsToBin

# Installing GRUB theme 
echo "Installing GRUB theme..."
sleep 1

sudo $DOTFILES_DIR/Apps/grub/install.sh -v

# First wal run
python $DOTFILES_DIR/Scripts/pythonScripts/wallpaperAndColorScheme.py

# Fix small error for VLC downloading
mkdir ~/.cache/vlc

#echo "Setting up Spicetify..."
#sleep 1

#spicetify backup apply enable-devtool
#spicetify update apply

echo "Setting up WPGTK theme... (CHANGE LATER WITH LXAPPEARANCE TO FLATCOLOR THEME AND ICON PACK)"
sleep 3

wpg-install.sh -i
wpg-install.sh -g

betterlockscreen -u $DOTFILES_DIR/Wallpapers/wallhaven-83do1o.jpg 

echo "And that's it!"
sleep 1


