#!/usr/bin/env sh

sudo yabai --install-sa
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Layout
yabai -m config layout bsp
yabai -m config window_placement first_child

yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.2
yabai -m config window_topmost on

yabai -m config window_shadow float

# yabai -m config mouse_modifier cmd
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize

# Spaces 
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five

# float preferences
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
# yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add title="^Opening .*$" manage=off layer=above
yabai -m rule --add app="^Godot" manage=off

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_border_color   0xff7aa2f7
yabai -m config normal_window_border_color   0xff444b6a