#!/usr/bin/env sh

sudo yabai --install-sa
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp
yabai -m config window_placement first_child

yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# yabai -m config mouse_modifier cmd
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Godot" manage=off