#!/bin/bash

nmcli device disconnect wlp7s0 
nmcli device disconnect enp8s0 

wmctrl -c "telegram"
xdotool key --clearmodifiers ctrl+q

wmctrl -c "franz"
xdotool key --clearmodifiers ctrl+q

killall steam &

killall lutris &

killall gamehub &

