#!/bin/bash

nmcli device disconnect wlp7s0 
nmcli device disconnect enp8s0 

wmctrl -c "telegram"
#xdotool key ctrl+q

wmctrl -c "franz"
#xdotool key ctrl+q

killall telegram & 
killall telegram-desktop & 

killall franz & 

killall steam &

killall lutris &

killall gamehub &