#!/bin/bash

sudo pacman -S base-devel git subversion cmake libxi libxcursor libxrandr libxinerama

mkdir -p $HOME/blender-git

cd $HOME/blender-git

git clone https://git.blender.org/blender.git

mkdir -p ~/blender-git/lib

cd ~/blender-git/lib

svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64

cd linux_centos7_x86_64/boost

sudo cp -r include/* /include/
sudo cp -r lib/* /lib/

cd ~/blender-git/blender 

git submodule update --init --recursive
git submodule foreach git checkout master
git submodule foreach git pull --rebase origin master

make update
make full

sudo cp ~/blender-git/build_linux_full/bin/blender /bin

sudo cp ~/Documents/dotfiles/Configs/blender.desktop /usr/share/applications

