#!/bin/bash

# Install dependencies
yay -S quazip

cd $HOME/

mkdir krita-git

cd krita-git

mkdir build

mkdir install

git clone git://anongit.kde.org/krita.git

cd build

cmake ../krita -DCMAKE_INSTALL_PREFIX=$HOME/krita-git/install -DCMAKE_BUILD_TYPE=Release -DKRITA_DEVS=ON

make -j8

make install

sudo cp ../install/bin/krita /bin/

sudo cp $HOME/Documents/dotfiles/Configs/krita.desktop /usr/share/applications


