#!/bin/bash

#yay -S blender svn downgrade

#yay -R blender

read -p "I need to downgrade boost, and therefore switch to Manjaro Testing. Do you want to switch branches? (y/n) " answer

if [ $answer == "y" ]
then
    sudo pacman-mirrors --api --set-branch testing
    sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syyu
    downgrade boost boost-libs
else 
    exit
fi

mkdir $HOME/blender-git

cd $HOME/blender-git

git clone https://git.blender.org/blender.git

mkdir ~/blender-git/lib

cd ~/blender-git/lib

svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64

cd linux_centos7_x86_64/boost

sudo cp -r include/* /include/
sudo cp -r lib/* /lib/

#mkdir deps

#./blender/build_files/build_environment/install_deps.sh --with-all --skip-llvm --skip-boost --source $HOME/blender-git/deps

cd ~/blender-git/blender 

git submodule update --init --recursive
git submodule foreach git checkout master
git submodule foreach git pull --rebase origin master

make update
make

