#!/bin/bash

echo "Adding this folder to the PATH environment variable..."
sleep 1

DOTFILES_DIR=${PWD}

echo "

" | tee -a ~/.bashrc
echo "export DOTFILES_DIR=$DOTFILES_DIR" | tee -a ~/.bashrc
echo "export PATH=$PATH:$DOTFILES_DIR:$DOTFILES_DIR/Scripts/bashScripts:$DOTFILES_DIR/Scripts/setupScripts" | tee -a ~/.bashrc

# This is also done right now so that the rest of the script can go along nicely, even without a reboot
export DOTFILES_DIR=$DOTFILES_DIR
export PATH=$PATH:$DOTFILES_DIR:$DOTFILES_DIR/Scripts/bashScripts:$DOTFILES_DIR/Scripts/setupScripts

echo "Added!"
sleep 1
