#!/bin/bash

cd ~

mkdir -p krita-dev

cd krita-dev

mkdir build install

git clone https://invent.kde.org/reispedro/krita.git

cd krita 

# Make upstream be the source for Kritagi
git remote add upstream git://anongit.kde.org/krita.git

cd ~/krita-dev/build 

# Install packages, only for Arch-based systems
sudo pacman -S extra-cmake-modules python-pyqt5 libheif gsl fftw eigen quazip vc karchive kconfig kwidgetsaddons kwindowsystem kcompletion kcoreaddons kguiaddons ki18n kitemmodels kitemviews kcrash cmake poppler-qt5

cmake ../krita -DCMAKE_INSTALL_PREFIX=$HOME/krita-dev/install -DCMAKE_BUILD_TYPE=Debug -DKRITA_DEVS=ON

make --no-print-directory -j8 && make --no-print-directory install

# Executables are now in krita-dev/install/bin/krita

sudo cp ~/krita-dev/install/bin/krita /bin

sudo cp -r ~/krita-dev/install/share/* /usr/share
