#!/bin/bash

mkdir -p krita-git

sudo pip install beautifulsoup4

cd ~

mkdir krita-git

python $DOTFILES_DIR/Scripts/pythonScripts/updateKrita.py

sudo chmod u+x $HOME/krita-git/krita.appimage

sudo cp $DOTFILES_DIR/Configs/krita.desktop /usr/share/applications




