#!/bin/bash

laptop="laptop"
desktop="desktop"

# Essential software for rice
echo "Installing essential software for rice..."
sleep 0.5

yay -S wmctrl ranger pacmixer lightdm-webkit-theme-litarvan dmenu dunst ffmpegthumbnailer feh rofi polybar gsimplecal flameshot betterlockscreen wpgtk-git playerctl spicetify-cli lxappearance python-sh gotop fish compton-tryone-git

echo "Cleaning cache..."
sleep 0.5
yay -Sc

echo "Updating system..."
sleep 0.5
yay

