#!/bin/bash

sudo pacman -S scons pkgconf gcc libxcursor libxinerama libxi libxrandr mesa glu alsa-lib pulseaudio freetype2 yasm

cd $HOME/

git clone https://github.com/godotengine/godot.git godot-git

cd godot-git

scons -j8 platform=x11

cd bin

#mv godot.linuxbsd.tools.64 godot

#sudo cp godot /bin

#sudo cp $DOTFILES_DIR/Configs/godot.desktop /usr/share/applications
