#!/bin/bash

mkdir -p krita-git

cd krita-git 

mkdir build 

mkdir install 

git clone git://anongit.kde.org/krita.git

cd build 

yay -S extra-cmake-modules python-qt5 sip libheif gsl fftw eigen quazip vc poppler-qt5

cmake ../krita -DCMAKE_INSTALL_PREFIX=$HOME/krita-git/install -DCMAKE_BUILD_TYPE=Release -DKRITA_DEVS=ON

make --no-print-directory -j8

make install

sudo cp ~/krita-git/install/bin/krita /bin

sudo cp -r ~/krita-git/install/share/* /usr/share




