#!/bin/bash

sudo cp $DOTFILES_DIR/Scripts/setupScripts/installBlender /bin
sudo cp $DOTFILES_DIR/Scripts/setupScripts/installGodot /bin
sudo cp $DOTFILES_DIR/Scripts/setupScripts/installKrita /bin
sudo cp $DOTFILES_DIR/Scripts/bashScripts/newsAndEntertainmentSync /bin
sudo cp $DOTFILES_DIR/Scripts/bashScripts/killDistractions /bin
sudo cp $DOTFILES_DIR/Scripts/bashScripts/resync /bin


sudo cp $DOTFILES_DIR/Scripts/setupScripts/update* /bin