#!/bin/bash


git chek

echo "Got you fam, installing on $device."
./Scripts/Scripts/add-to-path

create-base-files

install-rice

# Remove fish intro message
echo 'set -U fish_greeting ""' >> .config/fish/config.fish

setup-lightdm

setup-spicetify

# Fix small ranger error 
echo "set preview_script $HOME/.config/ranger/scope.sh" >> Apps/ranger/rc.conf

echo "\nSetting up $device configurations..."
sleep 1

update

install-fonts
	
if [ $device == $laptop ]
then
	polybar main

	echo "Configuring TLP for better battery management..."
	sleep 1

	./setupTLP

	read -p "Do you want to setup Prime? (y/n)  " answer

	if [ $answer == "y" ]
	then 
		sudo pacman -S nvidia lib32-nvidia-utils xf86-video-intel nvidia-prime
		sudo mv $DOTFILES_DIR/Configs/30-nvidia.conf /etc/X11/xorg.conf.d/
	fi 

elif [ $device == $desktop ]
then
	./tabletConfig
	polybar left && polybar right
fi

# Installing GRUB theme 
echo "Installing GRUB theme..."
sleep 1

sudo $DOTFILES_DIR/Apps/grub/install.sh -v

# First wal run
python $DOTFILES_DIR/Scripts/pythonScripts/wallpaper-change.py

# Fix small error for VLC downloading
mkdir ~/.cache/vlc

wpg-install.sh -i
wpg-install.sh -g

betterlockscreen -u $DOTFILES_DIR/Wallpapers/wallhaven-83do1o.jpg 

echo "If you want to configure VPN, you can do it now."
sleep 3

echo "And that's it! Exiting."
sleep 2


