#!/bin/bash

sudo rm -rf /usr/share/krita*
sudo rm -rf /usr/share/applications/krita*
sudo rm -rf /usr/share/color/icc/krita*
sudo rm -rf /usr/share/icons/hicolor/1024x1024/apps/krita.png 
sudo rm -rf /usr/share/icons/hicolor/128x128/apps/krita.png 
sudo rm -rf /usr/share/icons/hicolor/16x16/apps/krita.png 
sudo rm -rf /usr/share/icons/hicolor/22x22/apps/krita.png 
sudo rm -rf /usr/share/icons/hicolor/256x256/apps/krita.png 
sudo rm -rf /usr/share/icons/hicolor/32x32/apps/krita.png 
sudo rm -rf /usr/share/icons/hicolor/48x48/apps/krita.png 
sudo rm -rf /usr/share/icons/hicolor/512x512/apps/krita.png 
sudo rm -rf /usr/share/icons/hicolor/64x64/apps/krita.png 

sudo rm -rf /usr/share/icons/hicolor/1024x1024/mimetypes/application-x-krita.png
sudo rm -rf /usr/share/icons/hicolor/128x128/mimetypes/application-x-krita.png
sudo rm -rf /usr/share/icons/hicolor/16x16/mimetypes/application-x-krita.png
sudo rm -rf /usr/share/icons/hicolor/22x22/mimetypes/application-x-krita.png
sudo rm -rf /usr/share/icons/hicolor/256x256/mimetypes/application-x-krita.png
sudo rm -rf /usr/share/icons/hicolor/32x32/mimetypes/application-x-krita.png
sudo rm -rf /usr/share/icons/hicolor/48x48/mimetypes/application-x-krita.png
sudo rm -rf /usr/share/icons/hicolor/512x512/mimetypes/application-x-krita.png
sudo rm -rf /usr/share/icons/hicolor/64x64/mimetypes/application-x-krita.png
sudo rm -rf /usr/bin/krita
sudo rm -rf /usr/share/applications/org.kde.krita*
sudo rm -rf /usr/share/color-schemes/Krita*
sudo rm -rf /usr/share/icons/hicolor/scalable/apps/krita*
sudo rm -rf /usr/share/metainfo/org.kde.krita*

