#!/bin/bash

echo "Adding this folder to the PATH environment variable... (requires sudo)"
sleep 1

DOTFILES_DIR=${PWD}

sudo touch /etc/profile.d/dotfiles
echo "#!/bin/bash" | sudo tee -a /etc/profile.d/dotfiles
echo "export PATH=DOTFILES_DIR=$DOTFILES_DIR" | sudo tee -a /etc/profile.d/dotfiles
echo "export PATH=$PATH:$DOTFILES_DIR" | sudo tee -a /etc/profile.d/dotfiles

# This is also done right now so that the rest of the script can go along nicely, even without a reboot
export DOTFILES_DIR=$DOTFILES_DIR
export PATH=$PATH:$DOTFILES_DIR

echo "Added!"
sleep 1
