#!/bin/bash

rm -rf ~/.wine*
rm -f  ~/.local/share/mime/packages/x-wine-e*
rm -f  ~/.local/share/mime/application/x-wine-*
rm -f  ~/.local/share/icons/hicolor/*/apps/application-x-wine-*
rm -f  ~/.local/share/applications/wine-*
rm -f  ~/.local/share/desktop-directories/wine-*
rm -f  ~/.local/share/icons/hicolor/*/apps/7765_*
rm -f  ~/.config/menus/applications-merged/wine-*
rm -rf ~/.local/share/wineprefixes
rm -rf ~/.local/share/applications/wine*